name: driver_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  custom_refresh_indicator: ^3.0.0
  dio: ^5.4.1
  draggable_home: ^1.0.5
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  mobile_scanner: ^4.0.0
  modal_progress_hud_nsn: ^0.5.1
  page_transition: ^2.1.0
  quickalert: ^1.0.2
  rubber: ^1.1.0
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  sliding_up_panel2: ^3.3.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/roboto/
    - google_fonts/pt_serif/
    - google_fonts/be_vietnam/
    - assets/images/
    - assets/videos/
