name: driver_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  modal_progress_hud_nsn: ^0.5.1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/roboto/
    - assets/images/
    - assets/videos/
